---
apiVersion: cert-manager.io/v1  # cert-manager version: v1
kind: Certificate
metadata:
  name: codequest-tls
  namespace: default
  labels:
    app: codequest
    component: certificate
    environment: production
    managed-by: cert-manager
    security-tier: critical
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    monitoring.codequest.io/enable: "true"
    alerts.codequest.io/expiry-notification: "true"
spec:
  # Certificate secret configuration
  secretName: codequest-tls-cert
  duration: 2160h  # 90 days
  renewalTime: 720h  # 30 days before expiry
  
  # Issuer reference for Let's Encrypt production
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  
  # Domain names to be included in the certificate
  dnsNames:
  - api.codequest.com
  - app.codequest.com
  - admin.codequest.com
  
  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  
  # Certificate usage configuration
  keyUsages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  
  # Certificate authority configuration
  isCA: false
  
  # Subject information
  subject:
    organizations:
    - CodeQuest
    organizationalUnits:
    - Platform Security