# cert-manager.io/v1 ClusterIssuer for automated TLS certificate management
# Version: cert-manager v1.12+
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: codequest
    component: cert-issuer
    environment: production
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    cert-manager.io/enable-certificate-owner-ref: "true"
spec:
  acme:
    # Production Let's Encrypt ACME server endpoint
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for important notifications about certificates
    email: admin@codequest.example.com
    # Reference to secret that will store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      # HTTP-01 challenge solver configuration
      - http01:
          ingress:
            class: nginx
            # Ensure Ingress resources are created in correct namespace
            podTemplate:
              metadata:
                labels:
                  app: codequest
                  component: cert-solver
              spec:
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1001
                  fsGroup: 1001
                # Resource limits for challenge solver pods
                resources:
                  requests:
                    cpu: 100m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 128Mi
                # Pod security settings
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
        # Selector for which domains this solver is applicable
        selector:
          matchLabels:
            cert-manager.io/solver: http01