apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: codequest
  labels:
    app: codequest
    component: backend
    environment: production
    managed-by: azure-key-vault
    rotation-schedule: 90-days
  annotations:
    azure.key-vault/enabled: "true"
    azure.key-vault/vault-name: "codequest-kv"
    azure.key-vault/polling-interval: "1h"
    security.codequest.io/last-rotated: "2024-01-01T00:00:00Z"
    security.codequest.io/rotation-policy: "automated"
type: Opaque
data:
  # Database Configuration
  DB_USERNAME: ${DB_USERNAME}  # Base64 encoded, sourced from Azure Key Vault
  DB_PASSWORD: ${DB_PASSWORD}  # Base64 encoded, sourced from Azure Key Vault
  DB_HOST: ${DB_HOST}  # Base64 encoded
  DB_PORT: ${DB_PORT}  # Base64 encoded
  DB_NAME: ${DB_NAME}  # Base64 encoded
  DB_SSL: ${DB_SSL}  # Base64 encoded
  DB_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT}  # Base64 encoded
  DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}  # Base64 encoded

  # Redis Configuration
  REDIS_HOST: ${REDIS_HOST}  # Base64 encoded
  REDIS_PORT: ${REDIS_PORT}  # Base64 encoded
  REDIS_PASSWORD: ${REDIS_PASSWORD}  # Base64 encoded, sourced from Azure Key Vault
  REDIS_TLS_ENABLED: ${REDIS_TLS_ENABLED}  # Base64 encoded

  # JWT Configuration
  JWT_SECRET: ${JWT_SECRET}  # Base64 encoded, sourced from Azure Key Vault
  JWT_EXPIRATION: ${JWT_EXPIRATION}  # Base64 encoded
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}  # Base64 encoded, sourced from Azure Key Vault
  JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}  # Base64 encoded

  # Azure DevOps Configuration
  ADO_CLIENT_ID: ${ADO_CLIENT_ID}  # Base64 encoded
  ADO_CLIENT_SECRET: ${ADO_CLIENT_SECRET}  # Base64 encoded, sourced from Azure Key Vault
  ADO_TENANT_ID: ${ADO_TENANT_ID}  # Base64 encoded
  ADO_SCOPE: ${ADO_SCOPE}  # Base64 encoded

  # Azure Service Principal Configuration
  AZURE_TENANT_ID: ${AZURE_TENANT_ID}  # Base64 encoded
  AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}  # Base64 encoded
  AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}  # Base64 encoded
  AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}  # Base64 encoded, sourced from Azure Key Vault
  AZURE_RESOURCE_GROUP: ${AZURE_RESOURCE_GROUP}  # Base64 encoded

  # Key Vault Configuration
  KEY_VAULT_NAME: ${KEY_VAULT_NAME}  # Base64 encoded
  KEY_VAULT_URI: ${KEY_VAULT_URI}  # Base64 encoded